### ISSUE TITLE
Basic configuration with multiple commits per day is failling

### ISSUE THREAD

**Issue by raphaelmatori** [bcanseco/github-contribution-graph-action#4]
Using below config, the server is sending thousands of commits in less than 2 minutes.:

```yml
# .github/workflows/main.yml

on:
  push:
    branches: [ master ]

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: you@youremail.com # replace me
        MAX_DAYS: 365
        MIN_COMMITS_PER_DAY: 1
        MAX_COMMITS_PER_DAY: 5
```

Expected: Maximum of 5 commits.
Tested using v1.1.0 and v1.2.0
